"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['chromedriver', 'text.txt']
OPTIONS = {
    'argv_emulation': True,
    'iconfile':'icon.icns',
    'plist': {
        'CFBundleName': "LetterToSoldier",
        'CFBundleDisplayName': "LetterToSoldier",
        'CFBundleGetInfoString': "Write letters to soldiers!",
        'CFBundleIdentifier': "com.hands.lettersoldier",
        'CFBundleVersion': "1.2.0",
        'CFBundleShortVersionString': "1.2.0",
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
